### ISSUE TITLE
部署线上第一次访问巨慢

### ISSUE THREAD

**Issue by Looooper** [ZHENFENG13/My-Blog#36]
部署到阿里云1核2G的云主机下第一次访问很慢。系统是CentOS7.2 64位 ,jre是ServerJRE 1.8
IDEA打成Jar包直接java -jar my-blog.jar启动。查看日志，第一次访问从收到用户请求到获取到DRUID连接池连接需要好长时间
2017-09-29 16:03:57.173 [http-nio-8080-exec-1] INFO  com.my.blog.website.interceptor.BaseInterceptor - 用户访问地址: /, 来路地址: 116.237.43.65
2017-09-29 16:15:35.666 [http-nio-8080-exec-1] INFO  javax.sql.DataSource - URL : http://116.196.83.87:8080/,IP : 116.237.43.65,CLASS_METHOD : com.my.blog.website.controller.IndexController.index,ARGS : [org.apache.catalina.connector.RequestFacade@6b9fcd9b, 12]

**Comment by troublrMan** [comment]
我的第一次也是有点慢 后期就还好

**Comment by Looooper** [comment]
多谢回复。我在macos windows ubuntu上部署都没问题，唯独centos特别慢。后来查阅网上博客得知是springboot内置的tomcat在处理第一个用户请求的时候，卡在生成sessionid那一步了。生成sessionid用到了java随机数。centos下的默认配置略有问题，解决方法之一是修改$JAVA_HOME/jre/lib/security/java.security文件中securerandom.source的值，从默认的file：/dev/random改为file：/dev/urandom。修改后第一次访问也基本能做到2秒内响应。

发自我的 iPad

在 2017年9月30日，下午4:17，troublrMan <notifications@github.com<mailto:notifications@github.com>> 写道：


我的第一次也是有点慢 后期就还好

**Comment by troublrMan** [comment]
我把原来的文件存储换成七牛的了  可以pr？






在 2017-10-25 13:36:43，"涵" <notifications@github.com> 写道：


Closed #36.

**Comment by troublrMan** [comment]
http://www.oschina.net/p/tale  您好，你的blog源项目系统的开源正在被别人用了， 不知道这个是你上传到开源中国的吗？







在 2017-10-25 13:36:43，"涵" <notifications@github.com> 写道：


Closed #36.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.




【网易自营|30天无忧退货】仅售同款价1/4！MUJI制造商“2017秋冬舒适家居拖鞋系列”限时仅34.9元>>
