### ISSUE TITLE
后台管理失效

### ISSUE THREAD

**Issue by YuukiZc** [ZHENFENG13/My-Blog#76]
后台管理中
A.发布博客功能失效
B.第二个模块管理模块失效
有可能造成的原因是:
1.pom.xml
由于clone的项目里application.properties中spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver爆红,原因是pom文件里的mysql-connector-java的版本过低于是我换成了 
<artifactId>mysql-connector-java</artifactId>
<version>6.0.6</version>
或网上其他解决方案是在数据库url后面加上 ?serverTimezone=GMT
但是我觉得问题不在这...求解..

**Comment by ZHENFENG13** [comment]
那你先连上数据库再说，看具体的报错日志，看你描述我也没办法确定具体的问题

**Comment by qumj123** [comment]
serverTimezone=GMT我的加上这段可以了，找不到后台入口

**Comment by YuukiZc** [comment]
问题解决了因为浏览器内核不兼容的原因. 后台要手动输入页面地址..login页面还是admin你试试看

**Comment by qumj123** [comment]
弄好了，谢谢，这项目是你自己写的吗，还是改的别人的？大神
------------------ 原始邮件 ------------------
发件人: "YuukiZc"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 下午5:48
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76)




问题解决了因为浏览器内核不兼容的原因. 后台要手动输入页面地址..login页面还是admin你试试看

**Comment by YuukiZc** [comment]
这个是楼主ZHENFENG13 这位是BOSS

**Comment by qumj123** [comment]
你知道怎么换模板吗？




------------------ 原始邮件 ------------------
发件人: "YuukiZc"<notifications@github.com>;
发送时间: 2019年6月14日(星期五) 下午5:51
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76)




这个是楼主ZHENFENG13 这位是BOSS

**Comment by ZHENFENG13** [comment]
> 你知道怎么换模板吗？
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "YuukiZc"<notifications@github.com>; 发送时间: 2019年6月14日(星期五) 下午5:51 收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>; 抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>; 主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76) 这个是楼主ZHENFENG13 这位是BOSS — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

MyBlogController代码里有个变量，改那个值就可以了，后面有时间会把这个功能做到后台管理系统里。

**Comment by qumj123** [comment]
好的。谢谢


------------------ 原始邮件 ------------------
发件人: "涵"<notifications@github.com>;
发送时间: 2019年6月17日(星期一) 上午9:39
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76)



 
你知道怎么换模板吗？
 …
 ------------------ 原始邮件 ------------------ 发件人: "YuukiZc"notifications@github.com; 发送时间: 2019年6月14日(星期五) 下午5:51 收件人: "ZHENFENG13/My-Blog"My-Blog@noreply.github.com; 抄送: "相濡以沫"305502220@qq.com;"Comment"comment@noreply.github.com; 主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76) 这个是楼主ZHENFENG13 这位是BOSS — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.
  
MyBlogController代码里有个变量，改那个值就可以了，后面有时间会把这个功能做到后台管理系统里。

**Comment by sinmusystems** [comment]
请问admin/login显示Error 500怎么解决。

**Comment by sinmusystems** [comment]
是浏览器内核不兼容的原因吗？需要用哪个游览器，chrome吗？

**Comment by qumj123** [comment]
解决了,谢谢。


------------------ 原始邮件 ------------------
发件人: "sinmusystems"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 晚上10:07
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76)




是浏览器内核不兼容的原因吗？需要用哪个游览器，chrome吗？

**Comment by qumj123** [comment]
500肯定是服务器异常了


------------------ 原始邮件 ------------------
发件人: "sinmusystems"<notifications@github.com>;
发送时间: 2019年7月11日(星期四) 晚上10:06
收件人: "ZHENFENG13/My-Blog"<My-Blog@noreply.github.com>;
抄送: "相濡以沫"<305502220@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ZHENFENG13/My-Blog] 后台管理失效 (#76)




请问admin/login显示Error 500怎么解决。

**Comment by YuukiZc** [comment]
> 是浏览器内核不兼容的原因吗？需要用哪个游览器，chrome
有些浏览器有2种模式比如360,一种是兼容模式,另外一种是极速模式.可以切换看看

**Comment by moscia** [comment]
我后台输入login报400错误是怎么回事
